// AUTO-GENERATED from Open-Paws/no-animal-violence. Do not edit directly.
"use strict";

const vscode = require("vscode");

const PATTERNS = [
		{
			pattern: /kill\s+two\s+birds\s+with\s+one\s+stone/gi,
			phrase: "kill two birds with one stone",
			suggest: "accomplish two things at once",
			alternatives: "\"accomplish two things at once\" or \"solve two problems with one action\" or \"hit two targets with one shot\"",
			reason: "This phrase frames killing animals as a routine way to solve a problem. Plain alternatives like 'accomplish two things at once' carry the same meaning without invoking harm.",
		},
		{
			pattern: /beat(ing)?\s+a\s+dead\s+horse/gi,
			phrase: "beat a dead horse",
			suggest: "belabor the point",
			alternatives: "\"belabor the point\" or \"go over old ground\" or \"repeat unnecessarily\"",
			reason: "This phrase uses an image of striking an animal's body as a metaphor for wasted effort. 'Belabor the point' is clearer and skips the imagery.",
		},
		{
			pattern: /(more\s+than\s+one|another|different|several)\s+way[s]?\s+to\s+skin\s+a\s+cat/gi,
			phrase: "more than one way to skin a cat",
			suggest: "more than one way to peel an orange",
			alternatives: "\"more than one way to peel an orange\" or \"multiple approaches available\" or \"several ways to do this\"",
			reason: "Cat skinning as a metaphor for having options. 'Multiple approaches available' or 'more than one way to peel an orange' carries the same meaning.",
		},
		{
			pattern: /let\s+the\s+cat\s+out\s+of\s+the\s+bag/gi,
			phrase: "let the cat out of the bag",
			suggest: "reveal the secret",
			alternatives: "\"reveal the secret\" or \"disclose prematurely\" or \"let it slip\"",
			reason: "Traced to fraudulent livestock markets and implies trapping animals. 'Reveal the secret' says the same thing more directly.",
		},
		{
			pattern: /open(ing)?\s+a\s+can\s+of\s+worms/gi,
			phrase: "open a can of worms",
			suggest: "create a complicated situation",
			alternatives: "\"create a complicated situation\" or \"uncover hidden problems\" or \"open Pandora's box\"",
			reason: "References worms packaged as live bait to catch and kill fish. 'Open a difficult topic' or 'uncover hidden problems' is more precise.",
		},
		{
			pattern: /wild\s+goose\s+chase/gi,
			phrase: "wild goose chase",
			suggest: "futile search",
			alternatives: "\"futile search\" or \"pointless pursuit\" or \"fool's errand\"",
			reason: "Casts pursuing a living bird as a pointless annoyance. 'Futile search' or 'fool's errand' says the same thing without the hunting framing.",
		},
		{
			pattern: /(like\s+)?shoot(ing)?\s+fish\s+in\s+a\s+barrel/gi,
			phrase: "shooting fish in a barrel",
			suggest: "trivially easy",
			alternatives: "\"trivially easy\" or \"a sure thing\" or \"no challenge at all\"",
			reason: "Mass-killing imagery used to mean 'easy.' 'Trivially easy' or 'a sure thing' says the same thing without it.",
		},
		{
			pattern: /flog(ging)?\s+a\s+dead\s+horse/gi,
			phrase: "flog a dead horse",
			suggest: "belabor the point",
			alternatives: "\"belabor the point\" or \"waste effort on a settled matter\" or \"repeat unnecessarily\"",
			reason: "Describes whipping an animal's corpse — the same image as 'beat a dead horse'. 'Belabor the point' is a direct replacement.",
		},
		{
			pattern: /(bigger|other)\s+fish\s+to\s+fry/gi,
			phrase: "bigger fish to fry",
			suggest: "more important matters to address",
			alternatives: "\"more important matters to address\" or \"bigger fish to free\"",
			reason: "Fish-as-food commodification for 'more important things.' 'More important matters' says the same thing.",
		},
		{
			pattern: /\bguinea\s+pig\b/gi,
			phrase: "guinea pig",
			suggest: "test subject",
			alternatives: "\"test subject\" or \"first to try\" or \"early adopter\"",
			reason: "Refers to using guinea pigs as expendable test subjects in harmful experiments. 'Test subject' or 'early adopter' is more precise in technical contexts.",
		},
		{
			pattern: /(?:bring(?:ing|s)?|brought)\s+home\s+the\s+bacon/gi,
			phrase: "bring home the bacon",
			suggest: "bring home the results",
			alternatives: "\"bring home the results\" or \"earn a living\" or \"win the prize\"",
			reason: "Describes slaughtered pig flesh as the fruit of success. 'Bring home the results' or 'earn a living' carries the same meaning.",
		},
		{
			pattern: /tak(e|ing|es|en)\s+the\s+bull\s+by\s+the\s+horns|took\s+the\s+bull\s+by\s+the\s+horns/gi,
			phrase: "take the bull by the horns",
			suggest: "tackle the problem directly",
			alternatives: "\"tackle the problem directly\" or \"face it head-on\" or \"confront the issue\"",
			reason: "Bullfighting/rodeo imagery. 'Tackle the problem directly' or 'face it head-on' is cleaner.",
		},
		{
			pattern: /(like\s+(a\s+)?)?lambs?\s+to\s+the\s+slaughter/gi,
			phrase: "lambs to the slaughter",
			suggest: "without resistance",
			alternatives: "\"without resistance\" or \"unknowingly walking into danger\" or \"defenseless\"",
			reason: "Direct slaughter imagery. 'Without resistance' or 'unknowingly walking into danger' captures the same meaning.",
		},
		{
			pattern: /(no|not\s+enough)\s+room\s+to\s+swing\s+a\s+cat/gi,
			phrase: "no room to swing a cat",
			suggest: "extremely tight space",
			alternatives: "\"extremely tight space\" or \"very cramped\"",
			reason: "Violent animal imagery for 'cramped.' 'Extremely tight space' says it directly.",
		},
		{
			pattern: /\bred\s+herring\b/gi,
			phrase: "red herring",
			suggest: "distraction",
			alternatives: "\"distraction\" or \"false lead\" or \"misleading clue\"",
			reason: "Originates from dead, smoked fish reportedly used to train hunting dogs. 'Distraction' or 'false lead' communicates the idea directly.",
		},
		{
			pattern: /curiosity\s+killed\s+the\s+cat/gi,
			phrase: "curiosity killed the cat",
			suggest: "curiosity backfired",
			alternatives: "\"curiosity backfired\" or \"being nosy caused trouble\" or \"curiosity led to trouble\"",
			reason: "A direct reference to killing a cat, used as a cautionary phrase. 'Curiosity backfired' or 'being nosy caused trouble' says the same thing.",
		},
		{
			pattern: /(running\s+around\s+)?like\s+a\s+chicken\s+with\s+(its|their)\s+head\s+cut\s+off/gi,
			phrase: "like a chicken with its head cut off",
			suggest: "like your hair is on fire",
			alternatives: "\"like your hair is on fire\" or \"in a panic\" or \"frantic and aimless\"",
			reason: "Graphic slaughter imagery used to describe panic. 'In a panic' or 'like your hair is on fire' captures the same thing.",
		},
		{
			pattern: /(your|their|his|her|my|our)\s+goose\s+is\s+cooked/gi,
			phrase: "your goose is cooked",
			suggest: "you're in trouble",
			alternatives: "\"you're in trouble\" or \"you're done for\" or \"you're dead in the water\"",
			reason: "Killing-and-cooking imagery used to mean someone is in trouble. 'You're in trouble' says it directly.",
		},
		{
			pattern: /thr(ow|owing|own|ew)(\s+(someone|them|him|her|us|me))?\s+to\s+the\s+wolves/gi,
			phrase: "throw someone to the wolves",
			suggest: "abandon to criticism",
			alternatives: "\"abandon to criticism\" or \"sacrifice someone\" or \"leave exposed\"",
			reason: "Frames a person as prey. 'Abandon to criticism' or 'leave exposed' carries the same meaning without the imagery.",
		},
		{
			pattern: /hook,?\s+line,?\s+and\s+sinker/gi,
			phrase: "hook, line, and sinker",
			suggest: "completely",
			alternatives: "\"completely\" or \"without question\" or \"fell for it entirely\"",
			reason: "References the equipment used to hook and kill fish. 'Completely' or 'without question' conveys total buy-in without the fishing imagery.",
		},
		{
			pattern: /clip(s|ped|ping)?\s+(someone's|their|his|her)?\s*wings/gi,
			phrase: "clip someone's wings",
			suggest: "restrict freedom",
			alternatives: "\"restrict freedom\" or \"limit options\" or \"hold back\"",
			reason: "Wing-clipping is a real physical mutilation done to captive birds. 'Restrict freedom' or 'limit options' says the same thing directly.",
		},
		{
			pattern: /straw\s+that\s+broke\s+the\s+camel'?s\s+back|last\s+straw/gi,
			phrase: "straw that broke the camel's back",
			suggest: "tipping point",
			alternatives: "\"tipping point\" or \"breaking point\" or \"final blow\"",
			reason: "Overloading a pack animal until its back breaks. 'Tipping point' or 'breaking point' carries the same meaning.",
		},
		{
			pattern: /(a\s+)?bird\s+in\s+the\s+hand(\s+is\s+worth)?/gi,
			phrase: "a bird in the hand",
			suggest: "a sure thing beats a possibility",
			alternatives: "\"a sure thing beats a possibility\" or \"a guaranteed outcome is worth more\"",
			reason: "References trapping wild birds. 'A sure thing beats a possibility' carries the same meaning.",
		},
		{
			pattern: /\beat(ing)?\s+crow\b/gi,
			phrase: "eat crow",
			suggest: "admit being wrong",
			alternatives: "\"admit being wrong\" or \"swallow one's pride\" or \"accept humiliation\"",
			reason: "References eating a killed bird as humiliating punishment. 'Admit being wrong' or 'swallow one's pride' says the same thing directly.",
		},
		{
			pattern: /f(ight|ights|ighting|ought)\s+like\s+cats\s+and\s+dogs/gi,
			phrase: "fight like cats and dogs",
			suggest: "constantly argue",
			alternatives: "\"constantly argue\" or \"clash frequently\"",
			reason: "Animal-fighting imagery. 'Constantly argue' or 'clash frequently' says it directly.",
		},
		{
			pattern: /(?:take|taking|took)\s+the\s+bait/gi,
			phrase: "take the bait",
			suggest: "fall for it",
			alternatives: "\"fall for it\" or \"be lured in\" or \"be deceived\"",
			reason: "References baiting hooks and traps to catch and kill animals. 'Fall for it' or 'be deceived' is more direct.",
		},
		{
			pattern: /(don'?t\s+)?count(ing)?\s+your\s+chickens(\s+before)?/gi,
			phrase: "don't count your chickens",
			suggest: "don't assume success prematurely",
			alternatives: "\"don't assume success prematurely\" or \"don't celebrate too early\"",
			reason: "Commodity framing of chickens as a yield to be counted. 'Don't assume success prematurely' says it directly.",
		},
		{
			pattern: /\blivestock\b/gi,
			phrase: "livestock",
			suggest: "farmed animals",
			alternatives: "\"farmed animals\"",
			reason: "Commodity framing that groups sentient beings as 'stock.' 'Farmed animals' keeps the meaning without the commodity framing.",
		},
		{
			pattern: /\bpoultry\b/gi,
			phrase: "poultry",
			suggest: "farmed birds",
			alternatives: "\"farmed birds\" or \"chickens and turkeys\"",
			reason: "Commodity framing for farmed birds. 'Farmed birds' or the specific species keeps the meaning without the commodity framing.",
		},
		{
			pattern: /gestation\s+(crate|stall)s?/gi,
			phrase: "gestation crate",
			suggest: "pregnancy cage",
			alternatives: "\"pregnancy cage\"",
			reason: "Industry euphemism for a metal enclosure so small a pregnant sow cannot turn around for her entire 3.5-month pregnancy. 'Pregnancy cage' is accurate.",
		},
		{
			pattern: /\bdepopulat(ion|ed|ing)\b/gi,
			phrase: "depopulation",
			suggest: "mass killing",
			alternatives: "\"mass killing\" or \"killed en masse\"",
			reason: "Industry euphemism for killing entire flocks or herds at once. 'Mass killing' is the accurate term. (Suppressed in database or population-statistics contexts where the word refers to removing records.)",
		},
		{
			pattern: /(meat[\s-]?packing|meat|packing|processing)\s+(plant|facility)s?/gi,
			phrase: "meat plant",
			suggest: "slaughterhouse",
			alternatives: "\"slaughterhouse\"",
			reason: "Industry euphemisms for slaughterhouse. 'Slaughterhouse' is the accurate term. (Suppressed in clearly non-animal contexts like data or chemical processing.)",
		},
		{
			pattern: /farrowing\s+(crate|stall)s?/gi,
			phrase: "farrowing crate",
			suggest: "birthing cage",
			alternatives: "\"birthing cage\"",
			reason: "Industry euphemism for the metal cage confining a sow during birth and nursing. 'Birthing cage' is accurate.",
		},
		{
			pattern: /battery[\s-]cage[ds]?/gi,
			phrase: "battery cage",
			suggest: "small wire cage",
			alternatives: "\"small wire cage\" or \"confined cage\"",
			reason: "Industry euphemism for wire enclosures that give each hen less floor space than a sheet of paper. 'Small wire cage' describes what it is.",
		},
		{
			pattern: /spent\s+hens?/gi,
			phrase: "spent hen",
			suggest: "hen killed after egg production declines",
			alternatives: "\"hen killed after egg production declines\"",
			reason: "'Spent' frames the hen as a depleted resource. Naming what actually happens — she is killed when her egg production falls — is more accurate.",
		},
		{
			pattern: /humane(ly)?\s+(slaughter(ed)?|killing|death)/gi,
			phrase: "humane slaughter",
			suggest: "slaughter",
			alternatives: "\"slaughter\" or \"killing\"",
			reason: "Industry oxymoron — a killing cannot be 'humane' to the one being killed. Drop the modifier and use 'slaughter' or 'killing.'",
		},
		{
			pattern: /\bbroiler\s+(chickens?|hens?)|broilers\b/gi,
			phrase: "broiler chicken",
			suggest: "chicken raised for meat",
			alternatives: "\"chicken raised for meat\"",
			reason: "Industry term that defines a chicken by its commercial purpose. 'Chicken raised for meat' is the human-readable version. (The kitchen appliance is not flagged.)",
		},
		{
			pattern: /don'?t\s+be\s+a\s+chicken/gi,
			phrase: "don't be a chicken",
			suggest: "don't hesitate",
			alternatives: "\"don't hesitate\" or \"be brave\" or \"go for it\"",
			reason: "Uses a chicken as an insult for cowardice. 'Don't hesitate' or 'be brave' is direct and doesn't rely on a demeaning stereotype.",
		},
		{
			pattern: /\bbadger(ed|ing|s)?\b/gi,
			phrase: "badger someone",
			suggest: "pester",
			alternatives: "\"pester\" or \"pressure\" or \"harass\"",
			reason: "Comes from badger-baiting, a blood sport where dogs were set on captive badgers. 'Pester' or 'pressure' carries the same meaning without the origin.",
		},
		{
			pattern: /\bferret(ed|ing)?\s+out\b/gi,
			phrase: "ferret out",
			suggest: "uncover",
			alternatives: "\"uncover\" or \"discover\" or \"dig up\"",
			reason: "Refers to the historical use of ferrets to flush rabbits out of burrows to be killed. 'Uncover' or 'dig up' works just as well.",
		},
		{
			pattern: /cattle[,]?\s+(not|vs\.?|versus)\s+pets|pets\s+not\s+cattle/gi,
			phrase: "cattle not pets",
			suggest: "ephemeral vs. persistent",
			alternatives: "\"ephemeral vs. persistent\" or \"disposable vs. unique\" or \"numbered vs. named\"",
			reason: "Infrastructure metaphor that Google's own style guide flags for removal as 'figurative language that relates to the slaughter of animals.' 'Ephemeral vs. persistent' or 'disposable vs. unique' captures the same architectural concept.",
		},
		{
			pattern: /canary\s+in\s+(a|the)\s+coal\s+mine/gi,
			phrase: "canary in a coal mine",
			suggest: "early warning signal",
			alternatives: "\"early warning signal\" or \"leading indicator\" or \"sentinel\"",
			reason: "Refers to canaries historically placed in coal mines to die first as a warning to miners. 'Early warning signal' or 'sentinel' conveys the meaning without the harm.",
		},
		{
			pattern: /fishing\s+expeditions?/gi,
			phrase: "fishing expedition",
			suggest: "exploratory investigation",
			alternatives: "\"exploratory investigation\" or \"speculative inquiry\" or \"unfocused search\"",
			reason: "Frames speculative inquiry as fishing — the metaphor softens the catch. 'Exploratory investigation' is clearer, especially in legal writing.",
		},
		{
			pattern: /\bsacred\s+cows?\b/gi,
			phrase: "sacred cow",
			suggest: "unquestioned belief",
			alternatives: "\"unquestioned belief\" or \"untouchable topic\" or \"protected assumption\"",
			reason: "Treats cattle as objects in an 'untouchable' metaphor while also trivializing Hindu beliefs. 'Unquestioned belief' or 'protected assumption' avoids both issues.",
		},
		{
			pattern: /\bscapegoat(ed|ing|s)?\b/gi,
			phrase: "scapegoat",
			suggest: "blame target",
			alternatives: "\"blame target\" or \"fall person\" or \"wrongly blamed\"",
			reason: "Originates from the ritual sacrifice of goats to carry away blame. 'Blame target' or 'wrongly blamed' is more precise.",
		},
		{
			pattern: /dead[\s_-]?cat[\s_-]?bounce/gi,
			phrase: "dead cat bounce",
			suggest: "temporary rebound",
			alternatives: "\"temporary rebound\" or \"false recovery\" or \"brief uptick\"",
			reason: "A financial term built on the image of a dead cat. 'Temporary rebound' or 'false recovery' is more professional and avoids the image.",
		},
		{
			pattern: /\bdog[\s-]eat[\s-]dog\b/gi,
			phrase: "dog-eat-dog",
			suggest: "ruthlessly competitive",
			alternatives: "\"ruthlessly competitive\" or \"cutthroat\" or \"fiercely competitive\"",
			reason: "Frames dogs as inherently violent toward each other as a model for competition. 'Ruthlessly competitive' or 'cutthroat' conveys the meaning without the stereotype.",
		},
		{
			pattern: /\bwhack[\s-]a[\s-]mole\b/gi,
			phrase: "whack-a-mole",
			suggest: "recurring problem",
			alternatives: "\"recurring problem\" or \"endless loop\" or \"unwinnable game\"",
			reason: "References a game built around repeatedly striking animals as they pop up. 'Recurring problem' or 'endless loop' describes the pattern more precisely.",
		},
		{
			pattern: /cash\s+cows?/gi,
			phrase: "cash cow",
			suggest: "moneymaker",
			alternatives: "\"moneymaker\" or \"profit center\" or \"reliable revenue source\"",
			reason: "Treats a cow as a thing to be extracted from for profit. 'Moneymaker' or 'profit center' carries the same meaning.",
		},
		{
			pattern: /\bsacrificial\s+lambs?\b/gi,
			phrase: "sacrificial lamb",
			suggest: "expendable person",
			alternatives: "\"expendable person\" or \"person set up to fail\" or \"someone sacrificed for others\"",
			reason: "References the ritual slaughter of lambs. 'Expendable person' or 'someone sacrificed for others' communicates the metaphor directly.",
		},
		{
			pattern: /\bsitting\s+ducks?\b/gi,
			phrase: "sitting duck",
			suggest: "easy target",
			alternatives: "\"easy target\" or \"vulnerable target\" or \"exposed\"",
			reason: "Hunting imagery — a duck in the open, easy to shoot. 'Easy target' or 'vulnerable target' says the same thing.",
		},
		{
			pattern: /\bopen\s+season\b/gi,
			phrase: "open season",
			suggest: "free-for-all",
			alternatives: "\"free-for-all\" or \"unrestricted criticism\" or \"no holds barred\"",
			reason: "Refers to the legal hunting period when killing animals is permitted. 'Free-for-all' or 'no holds barred' conveys the meaning without the hunting framing.",
		},
		{
			pattern: /put(s|ting)?(\s+(him|her|them))?\s+out\s+to\s+pasture/gi,
			phrase: "put out to pasture",
			suggest: "retire",
			alternatives: "\"retire\" or \"phase out\" or \"sunset\"",
			reason: "Refers to the farm practice of disposing of animals once they're no longer productive. 'Retire,' 'phase out,' or 'sunset' is clearer and carries no harm.",
		},
		{
			pattern: /\bdead\s+ducks?\b/gi,
			phrase: "dead duck",
			suggest: "lost cause",
			alternatives: "\"lost cause\" or \"doomed effort\" or \"foregone conclusion\"",
			reason: "Hunting imagery — a duck that has been shot and killed. 'Lost cause' or 'doomed effort' is just as expressive.",
		},
		{
			pattern: /\bcull(ed|ing|s)?\b/gi,
			phrase: "cull",
			suggest: "remove",
			alternatives: "\"remove\" or \"prune\" or \"trim\" or \"filter out\"",
			reason: "Euphemism used in wildlife management and farming for mass killing. 'Remove', 'prune', 'trim', or 'filter out' is accurate in technical contexts.",
		},
		{
			pattern: /\bveal(\s+cal(f|ves))?\b/gi,
			phrase: "veal",
			suggest: "calf flesh",
			alternatives: "\"calf flesh\" or \"calf meat\"",
			reason: "'Veal' softens 'slaughtered-calf flesh' via a Norman-French borrowing. In advocacy or industry-critical writing, 'calf flesh' names what it is. (Suppressed in recipes and cooking contexts.)",
		},
		{
			pattern: /\blame[\s-]duck\b/gi,
			phrase: "lame duck",
			suggest: "outgoing",
			alternatives: "\"outgoing\" or \"transitional\" or \"ineffective\"",
			reason: "Combines an ableist adjective with a reference to a bird unable to fly due to injury. 'Outgoing', 'transitional', or 'ineffective' is more precise.",
		},
		{
			pattern: /\bdebeak(ing|ed)|beak\s+(trimming|trim|conditioning)\b/gi,
			phrase: "debeaking",
			suggest: "beak amputation",
			alternatives: "\"beak amputation\" or \"beak mutilation\"",
			reason: "Industry euphemism for slicing or burning off hens' beaks, typically without anesthesia. 'Beak amputation' names what actually happens.",
		},
		{
			pattern: /\bdehorn(ing|ed)|disbud(ding|ded)\b/gi,
			phrase: "dehorning",
			suggest: "horn amputation",
			alternatives: "\"horn amputation\" or \"horn removal\"",
			reason: "Industry term for removing cattle horns, typically without anesthesia. 'Horn amputation' is accurate.",
		},
		{
			pattern: /tail[\s-]docking|tail\s+docked|docked\s+tail/gi,
			phrase: "tail docking",
			suggest: "tail amputation",
			alternatives: "\"tail amputation\"",
			reason: "Amputating pigs', sheep's, or dogs' tails. 'Tail amputation' is the accurate term.",
		},
		{
			pattern: /ear[\s-]notch(ing|ed)/gi,
			phrase: "ear notching",
			suggest: "ear mutilation",
			alternatives: "\"ear mutilation\"",
			reason: "Industry identification practice of cutting notches in animals' ears. 'Ear mutilation' names what it is.",
		},
		{
			pattern: /ventilation\s+shutdown(\s+plus)?|VSD\+|VSD\s+plus/gi,
			phrase: "ventilation shutdown",
			suggest: "mass killing by suffocation",
			alternatives: "\"mass killing by suffocation\" or \"heat-and-suffocation killing\"",
			reason: "Industry term for killing entire flocks by cutting off airflow — the animals die from suffocation and heat. 'Mass killing by suffocation' is the accurate term. (Suppressed in HVAC contexts.)",
		},
		{
			pattern: /(maceration\s+of\s+chicks|chick\s+maceration|macerat(ed|ing)\s+chicks)/gi,
			phrase: "maceration of chicks",
			suggest: "grinding newborn chicks alive",
			alternatives: "\"grinding newborn chicks alive\" or \"chick grinding\"",
			reason: "Industry euphemism for killing day-old male chicks by grinding them alive. Say what the process is. (Bare 'maceration' in culinary or chemistry contexts is not flagged.)",
		},
		{
			pattern: /\babattoirs?\b/gi,
			phrase: "abattoir",
			suggest: "slaughterhouse",
			alternatives: "\"slaughterhouse\"",
			reason: "French-derived euphemism for slaughterhouse. 'Slaughterhouse' is the accurate English term.",
		},
		{
			pattern: /rendering\s+(plant|facility)s?/gi,
			phrase: "rendering plant",
			suggest: "animal-body processing plant",
			alternatives: "\"animal-body processing plant\" or \"carcass-processing facility\"",
			reason: "Facility that processes animal bodies — roadkill, downed animals, slaughter byproducts — into meal, fat, and tallow. Naming it accurately makes the supply chain visible. (Only the full compound 'rendering plant' / 'rendering facility' is flagged; bare 'rendering' for graphics or UI is not.)",
		},
		{
			pattern: /\bstockyards?\b/gi,
			phrase: "stockyard",
			suggest: "slaughterhouse pens",
			alternatives: "\"slaughterhouse pens\" or \"live-animal market\"",
			reason: "Euphemism for pre-slaughter holding pens. 'Slaughterhouse pens' describes what the facility actually is.",
		},
		{
			pattern: /(laying|layer)\s+hens?/gi,
			phrase: "laying hen",
			suggest: "hen",
			alternatives: "\"hen\"",
			reason: "Defines a hen by her egg-laying function. When sex and species are relevant, 'hen' is sufficient.",
		},
		{
			pattern: /(dairy|beef)\s+(cow|cows|cattle)|meat\s+(birds?|rabbits?|goats?)/gi,
			phrase: "dairy cow",
			suggest: "cow",
			alternatives: "\"cow\" or \"the species name alone\"",
			reason: "Defines an animal by the product humans extract from them. The species name alone is sufficient unless the use is actively relevant.",
		},
		{
			pattern: /brood\s+sows?|breeding\s+(stock|pair)/gi,
			phrase: "brood sow",
			suggest: "pregnant pig",
			alternatives: "\"pregnant pig\" or \"nursing mother pig\"",
			reason: "Defines a female animal by her reproductive function. Name the individual directly where possible.",
		},
		{
			pattern: /cattle\s+calls?/gi,
			phrase: "cattle call",
			suggest: "open call",
			alternatives: "\"open call\" or \"mass audition\"",
			reason: "Likens human applicants to livestock being herded. 'Open call' or 'mass audition' carries the same meaning without the framing.",
		},
		{
			pattern: /pet\s+projects?/gi,
			phrase: "pet project",
			suggest: "side project",
			alternatives: "\"side project\" or \"passion project\"",
			reason: "Carries over the property framing of 'pet' (something owned) to the project. 'Side project' or 'passion project' captures the same idea without the ownership framing.",
		},
		{
			pattern: /humanely\s+(raised|produced|farmed)/gi,
			phrase: "humanely raised",
			suggest: "factory-farmed",
			alternatives: "\"factory-farmed\" or \"raised in [specific conditions]\"",
			reason: "USDA-unregulated marketing label — companies define their own standards, and the actual conditions often differ little from factory farming. Describe the actual conditions where possible.",
		},
		{
			pattern: /free[\s-]rang(e|ing)|free[\s-]roaming/gi,
			phrase: "free-range",
			suggest: "minimally accessible outdoor pen",
			alternatives: "\"minimally accessible outdoor pen\" or \"outdoor access (USDA minimum)\"",
			reason: "USDA requires only 'access to outdoors' — often a small door to a small porch that most birds never use. The label does not guarantee meaningful outdoor life.",
		},
		{
			pattern: /pasture[\s-]raised|pastured/gi,
			phrase: "pasture-raised",
			suggest: "raised on pasture (certifier-dependent)",
			alternatives: "\"raised on pasture (certifier-dependent)\"",
			reason: "Not USDA-regulated; the meaning depends on whichever certifier the producer chooses. Name the certifier and the actual conditions where possible.",
		},
		{
			pattern: /grass[\s-](fed|finished)/gi,
			phrase: "grass-fed",
			suggest: "grass-fed (USDA definition dropped 2016)",
			alternatives: "\"grass-fed (USDA definition dropped 2016)\" or \"forage-finished\"",
			reason: "Describes the cattle's feed, not their welfare. Slaughter, transport, and mother-calf separation happen the same way. The USDA dropped its 'grass-fed' definition in 2016; current usage is producer-defined.",
		},
		{
			pattern: /cage[\s-]free\s+(chicken|turkey|meat|pork|beef)/gi,
			phrase: "cage-free chicken",
			suggest: "crowded indoor housing",
			alternatives: "\"crowded indoor housing\" or \"barn-raised\"",
			reason: "Meaningless for meat birds — broiler chickens and turkeys are almost never caged in industrial production. The label implies a welfare improvement that doesn't exist. (Cage-free for eggs IS a meaningful distinction; that usage is not flagged.)",
		},
		{
			pattern: /Certified\s+Humane|Animal\s+Welfare\s+Approved|Global\s+Animal\s+Partnership|American\s+Humane\s+Certified|One\s+Health\s+Certified|GAP\s+(certified|Step(\s+\d)?)/gi,
			phrase: "Certified Humane",
			suggest: "name the certifier and standard",
			alternatives: "\"name the certifier and standard\"",
			reason: "Third-party welfare certifications with widely varying standards — some are meaningful (Animal Welfare Approved), others are marketing (American Humane Certified). Name the specific standard if relevant.",
		},
		{
			pattern: /(ethically|responsibly)\s+sourced\s+(meat|dairy|eggs|beef|pork|chicken)|happy\s+(meat|cows?)/gi,
			phrase: "ethically sourced meat",
			suggest: "describe the actual farm practices",
			alternatives: "\"describe the actual farm practices\"",
			reason: "Marketing language without a standard definition when applied to animal products. 'Ethically sourced' meat has no USDA definition. Describe the actual practices instead. (The phrase applied to coffee, chocolate, or textiles is not flagged.)",
		},
		{
			pattern: /dolphin[\s-]safe|line[\s-]caught|pole[\s-](and[\s-]line[\s-])?caught|sustainab(ly\s+caught|le\s+seafood)/gi,
			phrase: "dolphin-safe",
			suggest: "name the specific fishing method and bycatch statistics",
			alternatives: "\"name the specific fishing method and bycatch statistics\"",
			reason: "Addresses specific bycatch concerns but not fish suffering. Fish feel pain, suffocate on deck, or are crushed in nets regardless of how the boat avoids catching dolphins or catches fish one at a time.",
		},
		{
			pattern: /(feed|fed|feeding)\s+to\s+the\s+(lions|sharks|dogs)/gi,
			phrase: "feed to the lions",
			suggest: "sacrifice",
			alternatives: "\"sacrifice\" or \"leave exposed\" or \"abandon to attack\"",
			reason: "Human-as-prey imagery. 'Sacrifice' or 'leave exposed' captures the same meaning.",
		},
		{
			pattern: /(like\s+(a\s+)?)?pigs?\s+to\s+slaughter/gi,
			phrase: "like a pig to slaughter",
			suggest: "defenseless",
			alternatives: "\"defenseless\" or \"walking into disaster\"",
			reason: "Direct slaughter imagery. 'Defenseless' or 'walking into disaster' captures the same meaning.",
		},
		{
			pattern: /turkey[\s-]shoot/gi,
			phrase: "turkey shoot",
			suggest: "trivially easy win",
			alternatives: "\"trivially easy win\" or \"no-contest situation\" or \"walkover\"",
			reason: "One-sided-slaughter imagery for an easy win. 'Walkover' or 'trivially easy win' carries the same meaning.",
		},
		{
			pattern: /fox(es)?\s+(guarding\s+the|in\s+the)\s+hen[\s-]?house/gi,
			phrase: "fox guarding the henhouse",
			suggest: "conflict of interest",
			alternatives: "\"conflict of interest\" or \"the wrong person in charge\"",
			reason: "Frames predation as an inevitable natural order. 'Conflict of interest' or 'wrong person in charge' is the actual point being made.",
		},
		{
			pattern: /(like\s+a\s+)?bull\s+in\s+a\s+china\s+shop/gi,
			phrase: "bull in a china shop",
			suggest: "tornado in a glass factory",
			alternatives: "\"tornado in a glass factory\" or \"clumsy disruption\" or \"careless and destructive\"",
			reason: "Bull-as-clumsy-brute stereotype — actually originates from a cartoon, not reality. 'Clumsy disruption' or 'careless and destructive' is more accurate.",
		},
		{
			pattern: /build(s|ing)?\s+a\s+better\s+mousetrap|better\s+mousetrap/gi,
			phrase: "build a better mousetrap",
			suggest: "build a better mouse pad",
			alternatives: "\"build a better mouse pad\" or \"invent something better\"",
			reason: "Mouse-killing device as innovation metaphor. 'Invent something better' or 'build a better mouse pad' captures the idea.",
		},
		{
			pattern: /(packed|squeezed)\s+(in\s+)?like\s+sardines/gi,
			phrase: "packed in like sardines",
			suggest: "packed in like pickles",
			alternatives: "\"packed in like pickles\" or \"tightly crowded\" or \"crammed together\"",
			reason: "Accurately describes industrial fishing and canning — the 'imagery' is the reality. 'Tightly crowded' or 'packed in like pickles' works without invoking it.",
		},
		{
			pattern: /pull(s|ing|ed)?\s+the\s+wool\s+over/gi,
			phrase: "pull the wool over",
			suggest: "deceive",
			alternatives: "\"deceive\" or \"mislead\" or \"pull the polyester over your eyes\"",
			reason: "Wool (sheep exploitation) as a deception metaphor. 'Deceive' or 'mislead' is direct and clearer.",
		},
		{
			pattern: /(put(s|ting)?\s+)?lipstick\s+on\s+a\s+pig/gi,
			phrase: "lipstick on a pig",
			suggest: "superficially improve",
			alternatives: "\"superficially improve\" or \"disguise the flaw\" or \"dress up a bad product\"",
			reason: "Frames pigs as ugly objects. 'Superficially improve' or 'disguise the flaw' is the actual meaning.",
		},
		{
			pattern: /silk\s+purse\s+(out\s+of|from)\s+a\s+sow's\s+ear/gi,
			phrase: "silk purse out of a sow's ear",
			suggest: "diamond bracelet out of a lump of coal",
			alternatives: "\"diamond bracelet out of a lump of coal\" or \"transform something unpromising\"",
			reason: "Pig body parts framed as worthless. 'Transform something unpromising' carries the same meaning.",
		},
		{
			pattern: /black\s+sheep/gi,
			phrase: "black sheep",
			suggest: "outlier",
			alternatives: "\"outlier\" or \"misfit\" or \"odd one out\"",
			reason: "Commodifies sheep coat color as a family-shame metaphor, with racial baggage. 'Outlier' or 'odd one out' works.",
		},
		{
			pattern: /wol(f|ves)\s+in\s+sheep'?s\s+clothing/gi,
			phrase: "wolf in sheep's clothing",
			suggest: "deceiver in disguise",
			alternatives: "\"deceiver in disguise\" or \"hidden threat\" or \"threat wearing a friendly face\"",
			reason: "Wolves-as-deceivers trope. 'Hidden threat' or 'deceiver in disguise' carries the same meaning.",
		},
		{
			pattern: /chicken(s|ed|ing)\s+out|chicken\s+out/gi,
			phrase: "chicken out",
			suggest: "back out",
			alternatives: "\"back out\" or \"lose nerve\" or \"get cold feet\"",
			reason: "Chicken-as-coward framing. 'Back out' or 'lose nerve' carries the same meaning.",
		},
		{
			pattern: /feeding\s+frenz(y|ies)/gi,
			phrase: "feeding frenzy",
			suggest: "chaotic rush",
			alternatives: "\"chaotic rush\" or \"scramble to exploit\" or \"uncontrolled grab\"",
			reason: "Shark-predation imagery used for human behavior. 'Chaotic rush' or 'scramble to exploit' carries the same meaning.",
		},
		{
			pattern: /(smell[s]?\s+)?blood\s+in\s+the\s+water/gi,
			phrase: "blood in the water",
			suggest: "signs of weakness",
			alternatives: "\"signs of weakness\" or \"vulnerability visible\" or \"sensing a kill\"",
			reason: "Shark-predation imagery. 'Signs of weakness' or 'vulnerability visible' carries the same meaning.",
		},
		{
			pattern: /(circl(e|ing)\s+(like\s+)?vultures|vultures\s+circling)/gi,
			phrase: "circling like vultures",
			suggest: "waiting to exploit",
			alternatives: "\"waiting to exploit\" or \"hovering opportunistically\" or \"waiting for weakness\"",
			reason: "Species defamation — the 'circling vulture' framing is factually wrong (vultures are ecological cleaners, not predators) and has driven real persecution; vulture populations are crashing globally. 'Waiting to exploit' carries the same meaning.",
		},
		{
			pattern: /mad(der)?\s+(than|as)\s+a\s+wet\s+hen/gi,
			phrase: "madder than a wet hen",
			suggest: "furious",
			alternatives: "\"furious\" or \"livid\" or \"seething\"",
			reason: "References the farm practice of dunking broody hens in water to break their nesting instinct. 'Furious' or 'livid' says it directly.",
		},
		{
			pattern: /code\s+monkeys?/gi,
			phrase: "code monkey",
			suggest: "developer",
			alternatives: "\"developer\" or \"programmer\" or \"engineer\"",
			reason: "Frames programmers as trained animals, and compounds with the long history of 'monkey' used as a racial slur. 'Developer' or 'engineer' is the accurate term.",
		},
		{
			pattern: /(memory|CPU|bandwidth|resource|disk|space)\s+hog|hogging\s+(memory|CPU|bandwidth|resources|the)|hogs\s+the|hog\s+the\s+spotlight/gi,
			phrase: "memory hog",
			suggest: "resource-intensive",
			alternatives: "\"resource-intensive\" or \"heavy consumer\" or \"monopolizes\" or \"dominates\"",
			reason: "Builds on the pig-as-greedy stereotype (pigs are actually selective eaters). 'Resource-intensive' or 'monopolizes' is more accurate and avoids the framing.",
		},
		{
			pattern: /\bpig[\s-]?headed(ness)?\b/gi,
			phrase: "pigheaded",
			suggest: "obstinate",
			alternatives: "\"obstinate\" or \"inflexible\" or \"unreasonable\"",
			reason: "Pig-as-stubborn stereotype (pigs are intelligent, not stubborn). 'Obstinate' or 'unreasonable' says it directly.",
		},
		{
			pattern: /eat(s|ing|e)?\s+like\s+a\s+pig|ate\s+like\s+a\s+pig|pig(s|ged|ging)?\s+out/gi,
			phrase: "eat like a pig",
			suggest: "overeat",
			alternatives: "\"overeat\" or \"gorge\" or \"eat voraciously\"",
			reason: "Pig-as-glutton stereotype (actually wrong — pigs are selective eaters in natural conditions). 'Overeat' or 'gorge' says the same thing.",
		},
		{
			pattern: /sons?[\s-]of[\s-]a[\s-]bitch|sons\s+of\s+bitches/gi,
			phrase: "son of a bitch",
			suggest: "specific descriptor",
			alternatives: "\"specific descriptor\"",
			reason: "Female-dog insult that compounds misogyny with species defamation. A specific descriptor is clearer and doesn't land on anyone's mother or on dogs.",
		},
		{
			pattern: /\bsheeple\b/gi,
			phrase: "sheeple",
			suggest: "conformists",
			alternatives: "\"conformists\" or \"unquestioning followers\" or \"uncritical crowd\"",
			reason: "Coined term meaning 'sheep-people' — dehumanizes the target while defaming sheep (who are actually complex social animals). 'Conformists' or 'uncritical crowd' carries the same meaning.",
		},
		{
			pattern: /(loan|card)[\s-]sharks?/gi,
			phrase: "loan shark",
			suggest: "predatory lender",
			alternatives: "\"predatory lender\" or \"hustler\" or \"card hustler\"",
			reason: "Species-as-predator trope applied to exploitative humans, which misrepresents sharks and provides a convenient framing for financial harm. 'Predatory lender' or 'hustler' is direct and more accurate.",
		},
		{
			pattern: /vulture\s+(capitalist|capitalism|fund)s?/gi,
			phrase: "vulture capitalist",
			suggest: "predatory investor",
			alternatives: "\"predatory investor\" or \"scavenger capitalist\" or \"distressed-debt investor\"",
			reason: "Species defamation that drives real-world vulture persecution — global vulture populations are crashing largely from this kind of cultural framing. 'Predatory investor' names the behavior without defaming an ecologically critical species.",
		},
		{
			pattern: /weasel\s+words?|weasel(s|ed|ing)?\s+out/gi,
			phrase: "weasel words",
			suggest: "evasive language",
			alternatives: "\"evasive language\" or \"evade\" or \"slippery phrasing\"",
			reason: "Species-as-deceitful trope. 'Evasive language' or 'slippery phrasing' is more direct. (Wikipedia's Manual of Style uses 'weasel words' as an internal term of art; that context is suppressed.)",
		},
		{
			pattern: /leech(es|ed|ing)?\s+off|bloodsuckers?/gi,
			phrase: "leech off",
			suggest: "freeload",
			alternatives: "\"freeload\" or \"mooch\" or \"exploit\" or \"parasitic\"",
			reason: "Species-as-parasite trope. 'Freeload' or 'mooch' is direct. (Bare 'leech' in medical contexts — leeches are still used in some surgeries — is not flagged.)",
		},
		{
			pattern: /monkey\s+business|monkey(s|ing|ed)?\s+around|(make|makes|making|made)\s+a\s+monkey\s+of/gi,
			phrase: "monkey business",
			suggest: "mischief",
			alternatives: "\"mischief\" or \"fool around\" or \"tamper with\" or \"make a fool of\"",
			reason: "Primate-as-foolish stereotype with a long racial history. 'Mischief' or 'fool around' is direct and doesn't carry the baggage.",
		},
		{
			pattern: /not\s+my\s+(circus[,]?\s+not\s+my\s+monkeys?|monkeys?|circus)/gi,
			phrase: "not my circus, not my monkeys",
			suggest: "not my problem",
			alternatives: "\"not my problem\" or \"not my concern\" or \"not my mess to clean up\"",
			reason: "Direct reference to circus-animal exploitation. 'Not my problem' carries the same meaning.",
		},
		{
			pattern: /\bbird[\s-]?brain(ed)?\b/gi,
			phrase: "bird brain",
			suggest: "forgetful",
			alternatives: "\"forgetful\" or \"absent-minded\" or \"scatter-brained\"",
			reason: "Bird-as-stupid stereotype (corvids and parrots rank among the most cognitively sophisticated non-human animals). 'Forgetful' or 'absent-minded' is more accurate.",
		},
		{
			pattern: /foie[\s-]gras/gi,
			phrase: "foie gras",
			suggest: "force-fed duck liver",
			alternatives: "\"force-fed duck liver\" or \"force-fed goose liver\"",
			reason: "French for 'fat liver'; obscures that the product comes from force-feeding ducks or geese until their livers enlarge to ten times normal size. Name the process.",
		},
		{
			pattern: /\bchevon\b/gi,
			phrase: "chevon",
			suggest: "goat flesh",
			alternatives: "\"goat flesh\" or \"goat meat\"",
			reason: "Marketing-constructed word (coined in the 1920s) to make goat meat palatable to Anglophone consumers. 'Goat flesh' or 'goat meat' is accurate.",
		},
		{
			pattern: /\bsweetbreads?\b/gi,
			phrase: "sweetbread",
			suggest: "calf thymus",
			alternatives: "\"calf thymus\" or \"calf pancreas\" or \"lamb thymus\"",
			reason: "Opaque culinary term for calf or lamb thymus or pancreas. Naming the organ is clearer. (Suppressed in recipe/cooking contexts.)",
		},
		{
			pattern: /\bmutton\b/gi,
			phrase: "mutton",
			suggest: "sheep flesh",
			alternatives: "\"sheep flesh\" or \"sheep meat\"",
			reason: "'Mutton' obscures the species. 'Sheep flesh' names it. (Suppressed in recipe contexts.)",
		},
		{
			pattern: /\bvenison\b/gi,
			phrase: "venison",
			suggest: "deer flesh",
			alternatives: "\"deer flesh\" or \"deer meat\"",
			reason: "'Venison' obscures the species. 'Deer flesh' names it. (Suppressed in recipe or hunting-regulation contexts.)",
		},
		{
			pattern: /\bsquabs?\b/gi,
			phrase: "squab",
			suggest: "pigeon flesh",
			alternatives: "\"pigeon flesh\" or \"young pigeon meat\"",
			reason: "Marketing term for young pigeon raised for slaughter. 'Pigeon flesh' names what it is. (Suppressed in recipe contexts.)",
		},
		{
			pattern: /\bspare[\s-]?ribs\b/gi,
			phrase: "spare ribs",
			suggest: "pig ribs",
			alternatives: "\"pig ribs\"",
			reason: "'Spare' frames body parts as disposable/extra. 'Pig ribs' is accurate. (Suppressed in recipe/BBQ contexts.)",
		},
		{
			pattern: /\b(genuine|real|top[\s-]grain|full[\s-]grain)?\s*leather\b/gi,
			phrase: "leather",
			suggest: "cow skin",
			alternatives: "\"cow skin\" or \"animal skin\" or \"vegan leather\" or \"synthetic leather\" or \"plant leather\"",
			reason: "'Leather' obscures that the material is the skin of a killed cow (or pig, sheep, etc.). In advocacy or supply-chain writing, naming it is clearer. Suppressed in fashion/product contexts where the industry term is expected.",
		},
		{
			pattern: /\b(merino\s+|lambs)?wool\b/gi,
			phrase: "wool",
			suggest: "sheep hair",
			alternatives: "\"sheep hair\" or \"synthetic fiber\" or \"plant fiber\"",
			reason: "'Wool' obscures that the fiber is sheep hair, usually from sheep bred for extreme coat yields (mulesing, shearing injury, eventual slaughter). Advocacy writing names it directly. Suppressed in textile/fashion contexts.",
		},
		{
			pattern: /down\s+(feathers|jacket|comforter|pillow|filling)|(goose|duck)\s+down/gi,
			phrase: "down feathers",
			suggest: "plant-based insulation",
			alternatives: "\"plant-based insulation\" or \"synthetic fill\" or \"recycled fill\"",
			reason: "Down is plucked from ducks and geese, often while alive and distressed. 'Plant-based insulation' or 'synthetic fill' describes the alternative. Bare 'down' (direction) is NOT flagged — only product compounds.",
		},
		{
			pattern: /\bcashmere|mohair|angora\b/gi,
			phrase: "cashmere",
			suggest: "goat hair",
			alternatives: "\"goat hair\" or \"rabbit hair\" or \"recycled fiber\" or \"synthetic alternative\"",
			reason: "Luxury-marketing names that obscure the animal source. Cashmere and mohair come from goats; angora comes from rabbits (who are often plucked live and injured). Naming the species is clearer in advocacy writing.",
		},
		{
			pattern: /\b(pure\s+|mulberry\s+|raw\s+)?silk\b/gi,
			phrase: "silk",
			suggest: "plant silk",
			alternatives: "\"plant silk\" or \"peace silk\" or \"synthetic silk\" or \"recycled fiber\"",
			reason: "Silk production typically requires boiling silkworms alive inside their cocoons to prevent the thread from breaking. Peace silk, plant silk, and synthetics avoid this. Suppressed in textile/fashion contexts.",
		},
		{
			pattern: /royal\s+jelly|beeswax|propolis/gi,
			phrase: "royal jelly",
			suggest: "plant alternative",
			alternatives: "\"plant alternative\" or \"candelilla wax\" or \"carnauba wax\" or \"soy wax\"",
			reason: "Bee products are extracted through industrial beekeeping, which involves queen-clipping, smoke stressing, and often the destruction of hives. Plant-based waxes (candelilla, carnauba, soy) serve most of the same purposes.",
		},
		{
			pattern: /down(ed|er)\s+(animal|cow|cattle|pig)s?/gi,
			phrase: "downed animal",
			suggest: "animal too sick or injured to walk",
			alternatives: "\"animal too sick or injured to walk\" or \"collapsed animal\"",
			reason: "'Downed' uses passive voice to elide why the animal is on the ground — untreated injury or illness in transport or on the farm. 'Too sick to walk' names the condition.",
		},
		{
			pattern: /(artificial|forced)\s+insemination|AI\s+in\s+(cattle|cows|dairy|pigs|sheep|swine)/gi,
			phrase: "artificial insemination",
			suggest: "forced impregnation",
			alternatives: "\"forced impregnation\"",
			reason: "Industry-standard procedure involving restraint and reproductive invasion. 'Forced impregnation' is the accurate term when the animal cannot consent. (The bare abbreviation 'AI' is not flagged — too much overlap with artificial intelligence. The rule fires only on the specific animal-ag compounds.)",
		},
		{
			pattern: /\bfarrow(ing|ed)\b/gi,
			phrase: "farrowing",
			suggest: "giving birth (for pigs)",
			alternatives: "\"giving birth (for pigs)\" or \"piglet-birthing\"",
			reason: "Industry verb that erases the individual animal giving birth. 'Giving birth' is the plain-language version. (The compound 'farrowing crate' is flagged by its own rule.)",
		},
		{
			pattern: /live\s+(export(s|ing)?|transport|shipment)/gi,
			phrase: "live export",
			suggest: "transport to slaughter",
			alternatives: "\"transport to slaughter\" or \"export for slaughter\"",
			reason: "Industry term for loading animals onto ships or trucks for days-to-weeks journeys to overseas slaughter. 'Transport to slaughter' names the destination.",
		},
		{
			pattern: /(pork|beef|dairy|poultry|veal|egg)\s+industry/gi,
			phrase: "pork industry",
			suggest: "pig-flesh industry",
			alternatives: "\"pig-flesh industry\" or \"cow-flesh industry\" or \"cow-milk industry\" or \"chicken-flesh industry\"",
			reason: "Each term names the product rather than the species it comes from. Naming the species (e.g. 'pig-flesh industry') makes the supply chain visible. Low priority — use in advocacy writing, not general documentation.",
		},
		{
			pattern: /trophy\s+(hunt(ing|er|ers)?|kill(s)?)/gi,
			phrase: "trophy hunting",
			suggest: "killing for display",
			alternatives: "\"killing for display\" or \"recreational killing\"",
			reason: "Frames a killed animal as an achievement to be displayed. 'Killing for display' or 'recreational killing' names the activity.",
		},
		{
			pattern: /big[\s-]game\s+hunt(ing|er|ers)?/gi,
			phrase: "big-game hunter",
			suggest: "large-animal hunter",
			alternatives: "\"large-animal hunter\" or \"elephant/lion/rhino hunter\"",
			reason: "'Big game' frames large wild animals as sport objects existing for human recreation. 'Large-animal hunter' names it; better still, name the species (elephant, lion, rhino).",
		},
		{
			pattern: /sport[\s]?fishing|recreational\s+fishing|game\s+fishing/gi,
			phrase: "sport fishing",
			suggest: "recreational fishing (if literal)",
			alternatives: "\"recreational fishing (if literal)\" or \"recreational killing of fish\"",
			reason: "'Sport' frames killing fish as leisure. In contexts critical of the activity, 'recreational killing of fish' is accurate. (In neutral angling-industry writing, the scanner adds noise; tune the context or disable in those files.)",
		},
		{
			pattern: /catch[\s-]and[\s-]release/gi,
			phrase: "catch and release",
			suggest: "capture and release",
			alternatives: "\"capture and release\" or \"captured and released (with injury)\"",
			reason: "Frames hook injury, exhaustion, and stress as harmless. Studies show significant post-release mortality, especially for species caught from deep water. 'Capture and release' is more neutral.",
		},
		{
			pattern: /thin(s|ning|ned)?\s+(out\s+)?the\s+herd/gi,
			phrase: "thin the herd",
			suggest: "reduce numbers by killing",
			alternatives: "\"reduce numbers by killing\" or \"kill off\"",
			reason: "Culling euphemism that softens 'kill off selected animals.' 'Kill off' says it directly.",
		},
		{
			pattern: /humane\s+(traps?|removal|control)/gi,
			phrase: "humane trap",
			suggest: "non-lethal trap",
			alternatives: "\"non-lethal trap\" or \"non-lethal removal\" or \"live-catch trap\"",
			reason: "'Humane' sanitizes the practice. Say whether it's lethal or non-lethal directly — 'non-lethal trap' is clearer and testable.",
		},
		{
			pattern: /lethal\s+(removal|control|management)/gi,
			phrase: "lethal removal",
			suggest: "killing program",
			alternatives: "\"killing program\" or \"culling program\"",
			reason: "Bureaucratic language for killing programs. 'Killing program' says it plainly.",
		},
		{
			pattern: /(fur|mink|fox)\s+(farms?|ranch(es)?)/gi,
			phrase: "fur farm",
			suggest: "mink confinement facility",
			alternatives: "\"mink confinement facility\" or \"fox confinement facility\" or \"fur-industry facility\"",
			reason: "'Farm' or 'ranch' evokes pastoral imagery; these are intensive confinement facilities where animals live in wire cages before being gassed or electrocuted. Name them directly.",
		},
		{
			pattern: /fur[\s-]bearing\s+animals?/gi,
			phrase: "fur-bearing animal",
			suggest: "named species",
			alternatives: "\"named species\" or \"fur-industry species\"",
			reason: "Defines wild animals by a human use. Naming the species (foxes, minks, coyotes, bobcats, chinchillas) is clearer.",
		},
		{
			pattern: /\bby[\s-]?catch\b/gi,
			phrase: "bycatch",
			suggest: "incidental killing",
			alternatives: "\"incidental killing\" or \"non-target marine deaths\"",
			reason: "Neutralizes the massive incidental killing of non-target marine species — hundreds of thousands of dolphins, sea turtles, seabirds, and sharks each year. 'Incidental killing' names it.",
		},
		{
			pattern: /fish(ery)?\s+stocks?/gi,
			phrase: "fish stocks",
			suggest: "fish populations",
			alternatives: "\"fish populations\" or \"wild fish numbers\"",
			reason: "Commodity framing of marine life as a renewable resource. 'Fish populations' is neutral and accurate.",
		},
		{
			pattern: /\baquaculture|fish\s+farming\b/gi,
			phrase: "aquaculture",
			suggest: "industrial fish farming",
			alternatives: "\"industrial fish farming\" or \"intensive fish confinement\"",
			reason: "Neutral-sounding framing for intensive fish confinement and slaughter. In advocacy writing, 'industrial fish farming' is more accurate.",
		},
		{
			pattern: /cr(y|ied|ying|ies)\s+wolf/gi,
			phrase: "cry wolf",
			suggest: "raise false alarms",
			alternatives: "\"raise false alarms\" or \"create alert fatigue\" or \"sound unjustified alerts\"",
			reason: "Rooted in Aesop's fable, the phrase reinforces the wolf-as-menace framing that has driven centuries of wolf persecution. 'Raise false alarms' captures the meaning.",
		},
		{
			pattern: /pecking\s+orders?/gi,
			phrase: "pecking order",
			suggest: "hierarchy",
			alternatives: "\"hierarchy\" or \"chain of command\" or \"ranking\"",
			reason: "Derived from the actual behavior of hens in confinement, where crowding causes injurious pecking. 'Hierarchy' or 'chain of command' captures the same idea.",
		},
		{
			pattern: /play(s|ing|ed)?\s+cat\s+and\s+mouse|(cat\s+and\s+mouse\s+game|game\s+of\s+cat\s+and\s+mouse)/gi,
			phrase: "play cat and mouse",
			suggest: "drawn-out pursuit",
			alternatives: "\"drawn-out pursuit\" or \"back-and-forth chase\" or \"evasive pursuit\"",
			reason: "Predator-prey torture metaphor — the game is about prolonging the suffering. 'Drawn-out pursuit' captures the meaning.",
		},
		{
			pattern: /cat\s+(that|who)\s+(swallowed|ate)\s+the\s+canary|canary[\s-]eating\s+grin/gi,
			phrase: "cat that swallowed the canary",
			suggest: "smug with secret knowledge",
			alternatives: "\"smug with secret knowledge\" or \"self-satisfied grin\"",
			reason: "Predation imagery — a dead canary is the joke's punchline. 'Smug with secret knowledge' captures it.",
		},
		{
			pattern: /(chomping|champing|chomps|champs)\s+at\s+the\s+bit/gi,
			phrase: "chomping at the bit",
			suggest: "eager to start",
			alternatives: "\"eager to start\" or \"impatient to begin\" or \"raring to go\"",
			reason: "References the metal 'bit' forced into a horse's mouth; the phrase describes the horse's attempt to relieve it. 'Eager to start' says the same thing.",
		},
		{
			pattern: /whip(s|ped|ping)?\s+into\s+shape/gi,
			phrase: "whip into shape",
			suggest: "get organized",
			alternatives: "\"get organized\" or \"demand discipline\" or \"restore order\"",
			reason: "Whip-violence imagery from animal training. 'Get organized' or 'restore order' is direct. (Political 'whip' and culinary 'whip' — different usage — are suppressed.)",
		},
		{
			pattern: /whal(e|es|ing|ed)\s+on/gi,
			phrase: "whale on",
			suggest: "pummel",
			alternatives: "\"pummel\" or \"beat up\" or \"hammer\"",
			reason: "Whaling (whale slaughter) as metaphor for repeated hitting. 'Pummel' or 'hammer' is direct.",
		},
		{
			pattern: /fish\s+or\s+cut\s+bait/gi,
			phrase: "fish or cut bait",
			suggest: "decide",
			alternatives: "\"decide\" or \"commit or move on\"",
			reason: "Fishing imagery. 'Decide' or 'commit or move on' is direct.",
		},
		{
			pattern: /pull(s|ing|ed)?\s+a\s+rabbit\s+out\s+of\s+a\s+hat/gi,
			phrase: "pull a rabbit out of a hat",
			suggest: "pull a coin out of an ear",
			alternatives: "\"pull a coin out of an ear\" or \"magically solve\" or \"produce unexpectedly\"",
			reason: "Stage magic often uses live rabbits kept in distressing conditions. 'Magically solve' or 'produce unexpectedly' carries the meaning without referencing the practice.",
		},
		{
			pattern: /walk(s|ing|ed)?\s+on\s+eggshells/gi,
			phrase: "walking on eggshells",
			suggest: "walking on thin ice",
			alternatives: "\"walking on thin ice\" or \"treading carefully\" or \"being extra cautious\"",
			reason: "Commodifies eggs as fragile objects; erases the laying-hen origin. 'Walking on thin ice' carries the same meaning.",
		},
		{
			pattern: /put\s+(a|the)\s+\S+\s+out\s+of\s+(its|their|the)\s+misery|put\s+(it|them)\s+out\s+of\s+(its|their)\s+misery|put\s+out\s+of\s+(its|their|the)\s+misery/gi,
			phrase: "put a horse out of its misery",
			suggest: "end the suffering",
			alternatives: "\"end the suffering\" or \"end it mercifully\" or \"conclude a painful situation\"",
			reason: "Horse-killing idiom. 'End the suffering' carries the same meaning without the imagery.",
		},
		{
			pattern: /kill(ing)?\s+the\s+fatted\s+calf/gi,
			phrase: "kill the fatted calf",
			suggest: "celebrate grandly",
			alternatives: "\"celebrate grandly\" or \"roll out the red carpet\" or \"prepare a feast\"",
			reason: "Biblical animal-sacrifice imagery (Luke 15 — the Prodigal Son). 'Celebrate grandly' or 'roll out the red carpet' carries the same meaning.",
		},
		{
			pattern: /(acting\s+like\s+lemmings|lemming\s+(investor|investors|behavior)|like\s+lemmings)/gi,
			phrase: "acting like lemmings",
			suggest: "herd-following investor",
			alternatives: "\"herd-following investor\" or \"unquestioning crowd\" or \"uncritical followers\"",
			reason: "Based on a Disney hoax — the 1958 'White Wilderness' staged lemmings being driven off a cliff. Lemmings don't mass-suicide. The metaphor defames the species and misleads the reader.",
		},
		{
			pattern: /(you|little|filthy|dirty)\s+maggots?/gi,
			phrase: "you maggot",
			suggest: "specific descriptor",
			alternatives: "\"specific descriptor\"",
			reason: "Degrading insect insult. Most uses in documentation are quoting dialogue or user-generated content; otherwise, use a specific descriptor.",
		},
		{
			pattern: /(filthy|dirty|you|capitalist|fascist|bourgeois)\s+swine/gi,
			phrase: "filthy swine",
			suggest: "specific descriptor",
			alternatives: "\"specific descriptor\"",
			reason: "Pig-as-degraded pejorative. Naming the actual trait (greedy, exploitative, corrupt) is clearer. (Bare 'swine' in medical contexts like 'swine flu' is not flagged.)",
		},
		{
			pattern: /\bcat[\s-]?fights?\b/gi,
			phrase: "cat fight",
			suggest: "heated argument",
			alternatives: "\"heated argument\" or \"altercation\" or \"confrontation\"",
			reason: "Gendered insult — almost exclusively applied to women arguing, framing them as cats fighting. 'Heated argument' or 'altercation' is neutral.",
		},
		{
			pattern: /(humans?\s+and\s+animals|animals\s+and\s+(humans?|people)|people\s+and\s+animals|man\s+and\s+beast)/gi,
			phrase: "humans and animals",
			suggest: "humans and non-human animals",
			alternatives: "\"humans and non-human animals\" or \"humans and other animals\" or \"people and other animals\"",
			reason: "False dichotomy — humans ARE animals. The phrasing reproduces the speciesist framing animal-liberation writing opposes. 'Humans and other animals' preserves the meaning accurately.",
		},
		{
			pattern: /(pet|dog|cat|rabbit|bird)\s+owners?/gi,
			phrase: "pet owner",
			suggest: "pet guardian",
			alternatives: "\"pet guardian\" or \"dog guardian\" or \"cat guardian\" or \"human companion\"",
			reason: "Property framing — 'owner' treats sentient beings as possessions. 'Guardian' preserves the legal and caregiving relationship without the property connotation. Used in legal reform jurisdictions (e.g. Boulder CO, West Hollywood) since the early 2000s.",
		},
		{
			pattern: /own(s|ing|ed)?\s+a\s+(pet|dog|cat|rabbit|bird)/gi,
			phrase: "own a pet",
			suggest: "live with a companion animal",
			alternatives: "\"live with a companion animal\" or \"share a home with\" or \"care for a\"",
			reason: "Property framing applied to companion animals. 'Live with a dog' or 'share a home with a cat' captures the relationship without the ownership frame.",
		},
		{
			pattern: /(fish|shrimp|salmon|tilapia)\s+harvest(ing)?/gi,
			phrase: "fish harvest",
			suggest: "fish slaughter",
			alternatives: "\"fish slaughter\" or \"shrimp slaughter\" or \"salmon slaughter\"",
			reason: "Aquaculture euphemism for killing/slaughtering farmed fish/shrimp. 'Harvest' obscures the mass killing at the end of the grow-out phase.",
		},
		{
			pattern: /stocking\s+density(ies)?/gi,
			phrase: "stocking density",
			suggest: "crowding density",
			alternatives: "\"crowding density\" or \"confinement density\"",
			reason: "Industry term for extreme overcrowding in aquaculture tanks/ponds/net pens, where fish are packed at densities causing stress, disease, and cannibalism.",
		},
		{
			pattern: /(harvest|market)\s+size|slaughter\s+weight/gi,
			phrase: "harvest size",
			suggest: "slaughter size",
			alternatives: "\"slaughter size\" or \"killing weight\"",
			reason: "Euphemism for the size/weight at which farmed fish/shrimp are killed ('harvested').",
		},
		{
			pattern: /grow-out\s+(pond|tank|phase)/gi,
			phrase: "grow-out pond",
			suggest: "fattening pond",
			alternatives: "\"fattening pond\" or \"fattening tank\"",
			reason: "Final fattening phase before slaughter in aquaculture.",
		},
];

/**
 * @param {vscode.ExtensionContext} context
 */
function activate(context) {
	const collection = vscode.languages.createDiagnosticCollection("no-animal-violence");

	function analyzeDocument(document) {
		const diagnostics = [];
		const text = document.getText();

		for (const { pattern, phrase, suggest, alternatives, reason } of PATTERNS) {
			pattern.lastIndex = 0;
			let match;
			while ((match = pattern.exec(text)) !== null) {
				const startPos = document.positionAt(match.index);
				const endPos = document.positionAt(match.index + match[0].length);
				const range = new vscode.Range(startPos, endPos);
				const altsLabel = alternatives || `"${suggest}"`;
				const why = reason ? ` ${reason}` : "";
				const diagnostic = new vscode.Diagnostic(
					range,
					`Avoid "${phrase}".${why} Consider: ${altsLabel}`,
					vscode.DiagnosticSeverity.Warning,
				);
				diagnostic.source = "no-animal-violence";
				diagnostics.push(diagnostic);
			}
		}

		collection.set(document.uri, diagnostics);
	}

	if (vscode.window.activeTextEditor) {
		analyzeDocument(vscode.window.activeTextEditor.document);
	}

	context.subscriptions.push(
		vscode.workspace.onDidOpenTextDocument(analyzeDocument),
		vscode.workspace.onDidChangeTextDocument((e) => analyzeDocument(e.document)),
		vscode.workspace.onDidCloseTextDocument((doc) => collection.delete(doc.uri)),
		collection,
	);
}

function deactivate() {}

module.exports = { activate, deactivate };
